apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: three-tier-app
type: Opaque
data:
  DB_USER: eW91cnVzZXI=        # base64 for "youruser"
  DB_PASSWORD: eW91cnBhc3N3b3Jk # base64 for "yourpassword"
